# Generated by Django 5.1.5 on 2025-02-04 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_kwan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('kwan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.kwan')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.municipio')),
            ],
        ),
    ]
