# Generated by Django 5.1.5 on 2025-02-05 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_acudiente'),
    ]

    operations = [
        migrations.CreateModel(
            name='FechaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=100)),
                ('codigo_carnet', models.CharField(max_length=8)),
                ('academia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.academia')),
                ('acudiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.acudiente')),
                ('cinturon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cinturon')),
                ('eps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.entidadpromotorasalud')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.municipio')),
                ('profesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.profesion')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tipodocumento')),
                ('fecha_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fechapago')),
            ],
        ),
    ]
