# Generated by Django 5.1.5 on 2025-02-06 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_estudiante_aldia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.estudiante')),
            ],
        ),
    ]
