# Generated by Django 5.1.5 on 2025-02-12 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_estudiante_acudiente_alter_estudiante_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.estudiante')),
            ],
        ),
    ]
