# Generated by Django 5.1.5 on 2025-02-20 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_monitoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoria',
            name='horas_autorizadas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
